configuration:
  resources:
    - type: "open-ai-configuration"
      name: "OpenAI"
      configuration:
        access-key: "${secrets.open-ai.access-key}"
    - type: "vector-database"
      name: "AstraDatasource"
      configuration:
        service: "astra"
        clientId: "${secrets.astra.clientId}"
        secret: "${secrets.astra.secret}"
        database: "${secrets.astra.database}"
        token: "${secrets.astra.token}"