topics:
  - name: "questions-topic"
    creation-mode: create-if-not-exists
  - name: "answers-topic"
    creation-mode: create-if-not-exists
errors:
    on-failure: "skip"
pipeline:
  - name: "convert-to-structure"
    type: "document-to-json"
    input: "questions-topic"
    configuration:
      text-field: "question"
  - name: "compute-embeddings"
    type: "compute-ai-embeddings"
    configuration:
      model: "${secrets.open-ai.embeddings-model}"
      embeddings-field: "value.embeddings_vector"
      text: "{{ value.question }}"
      batch-size: 10
      flush-interval: 500
  - name: "lookup-related-documents"
    type: "query-vector-db"
    configuration:
      datasource: "AstraDatasource"
      query: "SELECT text FROM eduwise_default.documents ORDER BY embeddings_vector ANN OF ? LIMIT 5"
      fields:
        - "value.embeddings_vector"
      output-field: "value.related_documents"
  - name: "Format response"
    type: compute
    output: "answers-topic"
    configuration:
      fields:
        - name: "value"
          type: "STRING"
          expression: "value.related_documents"
