export const WEBSOCKET_URL = process.env.NEXT_PUBLIC_WEBSOCKET_URL || ''
export const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME || ''
export const TENANT = process.env.NEXT_PUBLIC_TENANT || ''
export const CONSUMER = process.env.NEXT_PUBLIC_CONSUMER || ''
export const PRODUCER = process.env.NEXT_PUBLIC_PRODUCER || ''
export const CREDENTIALS = process.env.NEXT_PUBLIC_CREDENTIALS || ''